In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_excel(r"C:\Users\DELL\Downloads\Date_Fruit_Datasets.xlsx",sheet_name='Date_Fruit_Datasets')

In [6]:
df.head()

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0  422163   2378.908    837.8484    645.6693        0.6373  733.1539   
1  338136   2085.144    723.8198    595.2073        0.5690  656.1464   
2  526843   2647.394    940.7379    715.3638        0.6494  819.0222   
3  416063   2351.210    827.9804    645.2988        0.6266  727.8378   
4  347562   2160.354    763.9877    582.8359        0.6465  665.2291   

   SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0    0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1    0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2    0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3    0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4    0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   

   KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  ALLdaub4RG  \
0      4.2287 -59191263232 -50714214400 -39922372608     58.7255     54.9554   
1      3.1704 -34233065472 -37462601728 -31477794816     50.0259     52.8168   
2      4.7192 -93948354560 -74738221056 -60311207936     65.4772     59.2860   
3      8.2618 -32074307584 -32060925952 -29575010304     43.3900     44.1259   
4      4.4146 -39980974080 -35980042240 -25593278464     52.7743     50.9080   

   ALLdaub4RB  Class  
0     47.8400  BERHI  
1     47.8315  BERHI  
2     51.9378  BERHI  
3     41.1882  BERHI  
4     42.6666  BERHI  

[5 rows x 35 columns]

In [7]:
df.shape

(898, 35)

In [8]:
df.describe()

AREA    PERIMETER   MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY  \
count     898.000000   898.000000   898.000000  898.000000    898.000000   
mean   298295.207127  2057.660953   750.811994  495.872785      0.737468   
std    107245.205337   410.012459   144.059326  114.268917      0.088727   
min      1987.000000   911.828000   336.722700    2.283200      0.344800   
25%    206948.000000  1726.091500   641.068650  404.684375      0.685625   
50%    319833.000000  2196.345450   791.363400  495.054850      0.754700   
75%    382573.000000  2389.716575   858.633750  589.031700      0.802150   
max    546063.000000  2811.997100  1222.723000  766.453600      1.000000   

          EQDIASQ    SOLIDITY    CONVEX_AREA      EXTENT  ASPECT_RATIO  ...  \
count  898.000000  898.000000     898.000000  898.000000    898.000000  ...   
mean   604.577938    0.981840  303845.592428    0.736267      2.131102  ...   
std    119.593888    0.018157  108815.656947    0.053745     17.820778  ...   
min     50.298400    0.836600    2257.000000    0.512300      1.065300  ...   
25%    513.317075    0.978825  210022.750000    0.705875      1.373725  ...   
50%    638.140950    0.987300  327207.000000    0.746950      1.524150  ...   
75%    697.930525    0.991800  388804.000000    0.775850      1.674750  ...   
max    833.827900    0.997400  552598.000000    0.856200    535.525700  ...   

           SkewRB  KurtosisRR  KurtosisRG  KurtosisRB     EntropyRR  \
count  898.000000  898.000000  898.000000  898.000000  8.980000e+02   
mean     0.250518    4.247845    5.110894    3.780928 -3.185021e+10   
std      0.632918    2.892357    3.745463    2.049831  2.037241e+10   
min     -1.029100    1.708200    1.607600    1.767200 -1.091224e+11   
25%     -0.196950    2.536625    2.508850    2.577275 -4.429444e+10   
50%      0.135550    3.069800    3.127800    3.080700 -2.826156e+10   
75%      0.593950    4.449850    7.320400    4.283125 -1.460482e+10   
max      3.092300   26.171100   26.736700   32.249500 -1.627316e+08   

          EntropyRG     EntropyRB  ALLdaub4RR  ALLdaub4RG  ALLdaub4RB  
count  8.980000e+02  8.980000e+02  898.000000  898.000000  898.000000  
mean  -2.901860e+10 -2.771876e+10   50.082888   48.805681   48.098393  
std    1.712952e+10  1.484137e+10   16.063125   14.125911   10.813862  
min   -9.261697e+10 -8.747177e+10   15.191100   20.524700   22.130000  
25%   -3.894638e+10 -3.564534e+10   38.224425   38.654525   39.250725  
50%   -2.620990e+10 -2.392928e+10   53.841300   50.337800   49.614100  
75%   -1.433105e+10 -1.660367e+10   63.063350   59.573600   56.666675  
max   -5.627727e+08 -4.370435e+08   79.828900   83.064900   74.104600  

[8 rows x 34 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Class"]=le.fit_transform(df["Class"])
df


AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0    422163  2378.9080    837.8484    645.6693        0.6373  733.1539   
1    338136  2085.1440    723.8198    595.2073        0.5690  656.1464   
2    526843  2647.3940    940.7379    715.3638        0.6494  819.0222   
3    416063  2351.2100    827.9804    645.2988        0.6266  727.8378   
4    347562  2160.3540    763.9877    582.8359        0.6465  665.2291   
..      ...        ...         ...         ...           ...       ...   
893  255403  1925.3650    691.8453    477.1796        0.7241  570.2536   
894  365924  2664.8230    855.4633    551.5447        0.7644  682.5752   
895  254330  1926.7360    747.4943    435.6219        0.8126  569.0545   
896  238955  1906.2679    716.6485    441.8297        0.7873  551.5859   
897  343792  2289.2720    823.8438    534.7757        0.7607  661.6113   

     SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0      0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1      0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2      0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3      0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4      0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   
..        ...          ...     ...           ...  ...         ...         ...   
893    0.9785       261028  0.7269        1.4499  ...      2.2423      2.3704   
894    0.9466       386566  0.6695        1.5510  ...      3.4109      3.5805   
895    0.9925       256255  0.7240        1.7159  ...      2.2759      2.5090   
896    0.9604       248795  0.6954        1.6220  ...      2.6769      2.6874   
897    0.9781       351472  0.6941        1.5405  ...      2.5138      3.0369   

     KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  \
0        4.2287 -59191263232 -50714214400 -39922372608     58.7255   
1        3.1704 -34233065472 -37462601728 -31477794816     50.0259   
2        4.7192 -93948354560 -74738221056 -60311207936     65.4772   
3        8.2618 -32074307584 -32060925952 -29575010304     43.3900   
4        4.4146 -39980974080 -35980042240 -25593278464     52.7743   
..          ...          ...          ...          ...         ...   
893      2.7202 -25296416768 -19168882688 -18473392128     49.0869   
894      3.9910 -31605219328 -21945366528 -19277905920     46.8086   
895      2.6951 -22242772992 -19594921984 -17592152064     44.1325   
896      2.7991 -26048595968 -21299822592 -19809978368     51.2267   
897      3.0865 -31983476736 -20482514944 -21219354624     47.3454   

     ALLdaub4RG  ALLdaub4RB  Class  
0       54.9554     47.8400      0  
1       52.8168     47.8315      0  
2       59.2860     51.9378      0  
3       44.1259     41.1882      0  
4       50.9080     42.6666      0  
..          ...         ...    ...  
893     43.0422     42.4153      6  
894     39.1046     36.5502      6  
895     40.7986     40.9769      6  
896     45.7162     45.6260      6  
897     38.6966     39.6738      6  

[898 rows x 35 columns]

In [10]:
y=df['Class']
y

0      0
1      0
2      0
3      0
4      0
      ..
893    6
894    6
895    6
896    6
897    6
Name: Class, Length: 898, dtype: int32

In [11]:
x=df.drop(['Class'],axis=1)
x

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0    422163  2378.9080    837.8484    645.6693        0.6373  733.1539   
1    338136  2085.1440    723.8198    595.2073        0.5690  656.1464   
2    526843  2647.3940    940.7379    715.3638        0.6494  819.0222   
3    416063  2351.2100    827.9804    645.2988        0.6266  727.8378   
4    347562  2160.3540    763.9877    582.8359        0.6465  665.2291   
..      ...        ...         ...         ...           ...       ...   
893  255403  1925.3650    691.8453    477.1796        0.7241  570.2536   
894  365924  2664.8230    855.4633    551.5447        0.7644  682.5752   
895  254330  1926.7360    747.4943    435.6219        0.8126  569.0545   
896  238955  1906.2679    716.6485    441.8297        0.7873  551.5859   
897  343792  2289.2720    823.8438    534.7757        0.7607  661.6113   

     SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  SkewRB  KurtosisRR  \
0      0.9947       424428  0.7831        1.2976  ...  0.6019      3.2370   
1      0.9974       339014  0.7795        1.2161  ...  0.4134      2.6228   
2      0.9962       528876  0.7657        1.3150  ...  0.9183      3.7516   
3      0.9948       418255  0.7759        1.2831  ...  1.8028      5.0401   
4      0.9908       350797  0.7569        1.3108  ...  0.8865      2.7016   
..        ...          ...     ...           ...  ...     ...         ...   
893    0.9785       261028  0.7269        1.4499  ... -0.1398      2.2423   
894    0.9466       386566  0.6695        1.5510  ...  0.5611      3.4109   
895    0.9925       256255  0.7240        1.7159  ...  0.2665      2.2759   
896    0.9604       248795  0.6954        1.6220  ...  0.5325      2.6769   
897    0.9781       351472  0.6941        1.5405  ...  0.4318      2.5138   

     KurtosisRG  KurtosisRB    EntropyRR    EntropyRG    EntropyRB  \
0        2.9574      4.2287 -59191263232 -50714214400 -39922372608   
1        2.6350      3.1704 -34233065472 -37462601728 -31477794816   
2        3.8611      4.7192 -93948354560 -74738221056 -60311207936   
3        8.6136      8.2618 -32074307584 -32060925952 -29575010304   
4        2.9761      4.4146 -39980974080 -35980042240 -25593278464   
..          ...         ...          ...          ...          ...   
893      2.3704      2.7202 -25296416768 -19168882688 -18473392128   
894      3.5805      3.9910 -31605219328 -21945366528 -19277905920   
895      2.5090      2.6951 -22242772992 -19594921984 -17592152064   
896      2.6874      2.7991 -26048595968 -21299822592 -19809978368   
897      3.0369      3.0865 -31983476736 -20482514944 -21219354624   

     ALLdaub4RR  ALLdaub4RG  ALLdaub4RB  
0       58.7255     54.9554     47.8400  
1       50.0259     52.8168     47.8315  
2       65.4772     59.2860     51.9378  
3       43.3900     44.1259     41.1882  
4       52.7743     50.9080     42.6666  
..          ...         ...         ...  
893     49.0869     43.0422     42.4153  
894     46.8086     39.1046     36.5502  
895     44.1325     40.7986     40.9769  
896     51.2267     45.7162     45.6260  
897     47.3454     38.6966     39.6738  

[898 rows x 34 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
SD=StandardScaler()
x=SD.fit_transform(x)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression
LG = LogisticRegression()
LG.fit(x_train, y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
y_pred1 = LG.predict(x_test)
y_pred1

array([2, 5, 2, 6, 0, 2, 3, 2, 2, 1, 1, 2, 2, 2, 4, 4, 6, 5, 6, 1, 5, 4,
       2, 4, 5, 2, 3, 6, 0, 5, 6, 2, 2, 4, 2, 5, 0, 2, 2, 5, 1, 4, 5, 5,
       1, 1, 1, 2, 2, 5, 4, 3, 2, 6, 2, 4, 6, 2, 2, 0, 3, 1, 2, 2, 2, 6,
       1, 2, 4, 4, 2, 2, 4, 6, 3, 4, 2, 4, 5, 4, 2, 1, 4, 3, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 1, 2, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 4, 4, 4, 1, 1, 5, 5, 4, 4, 2, 5, 1, 5, 5, 6, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 6, 6, 5, 2, 0, 0, 5, 6, 4, 6, 1,
       6, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 3, 2, 4, 1, 6, 5, 6, 6, 5,
       0, 1, 0, 2, 6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 0, 5, 2, 1, 2, 4, 4, 4,
       5, 4, 6, 6, 4, 2, 5, 5, 5, 1, 4, 1, 4, 1, 5, 6, 2, 0, 5, 6, 4, 3,
       6, 2, 6, 2, 2, 3, 2, 5, 2, 4, 0, 2, 6, 4, 2, 2, 4, 6, 5, 5, 5, 5,
       3, 4, 0, 4, 3, 5, 5, 2, 4, 1, 2, 3, 0, 3, 3, 4, 6, 2, 6, 4, 4, 5,
       4, 5, 6, 2, 3, 5])

In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred1, labels=[1,0]))

[[20  0]
 [ 0 16]]


In [18]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred1)
print(accuracy)
print(metrics.classification_report(y_test, y_pred1, labels=[1, 0]))

0.9259259259259259
              precision    recall  f1-score   support

           1       0.77      0.71      0.74        28
           0       0.89      0.94      0.91        17

   micro avg       0.82      0.80      0.81        45
   macro avg       0.83      0.83      0.83        45
weighted avg       0.81      0.80      0.81        45



In [19]:
from sklearn.neighbors import KNeighborsClassifier
KNN= KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN.fit(x_train, y_train)

KNeighborsClassifier()

In [20]:
y_pred2 = KNN.predict(x_test)


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred2, labels=[1,0])
ac = accuracy_score(y_test, y_pred2)
print(cm)
print(ac)

[[23  0]
 [ 0 15]]
0.9111111111111111


In [23]:
print(metrics.classification_report(y_test, y_pred2, labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.70      0.82      0.75        28
           0       0.83      0.88      0.86        17

   micro avg       0.75      0.84      0.79        45
   macro avg       0.77      0.85      0.81        45
weighted avg       0.75      0.84      0.79        45



In [24]:
from sklearn.tree import DecisionTreeClassifier


In [25]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [26]:
y_pred3 = dtc.predict(x_test)
y_pred3

array([2, 5, 2, 6, 0, 2, 0, 2, 2, 2, 1, 2, 2, 2, 4, 1, 6, 5, 1, 1, 5, 0,
       2, 4, 5, 2, 0, 6, 0, 5, 6, 2, 2, 4, 2, 5, 0, 2, 1, 5, 6, 4, 5, 5,
       1, 2, 1, 2, 2, 5, 4, 0, 2, 6, 2, 4, 6, 2, 2, 0, 0, 1, 2, 1, 2, 1,
       1, 2, 4, 4, 2, 2, 4, 6, 0, 4, 2, 4, 5, 3, 2, 1, 3, 6, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 2, 1, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 4, 1, 4, 6, 1, 5, 5, 4, 4, 2, 5, 1, 5, 5, 6, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 1, 5, 6, 6, 5, 2, 0, 0, 5, 1, 4, 6, 1,
       4, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 4, 2, 4, 1, 6, 5, 6, 6, 5,
       0, 1, 0, 2, 1, 5, 2, 3, 1, 0, 2, 0, 0, 5, 0, 5, 2, 6, 2, 4, 6, 4,
       5, 4, 6, 6, 4, 2, 5, 5, 5, 6, 4, 6, 4, 1, 5, 1, 2, 0, 5, 1, 4, 3,
       6, 1, 6, 2, 2, 0, 2, 5, 2, 4, 0, 2, 6, 6, 2, 2, 4, 6, 5, 5, 5, 5,
       3, 4, 0, 4, 0, 0, 5, 2, 4, 1, 1, 0, 3, 3, 3, 4, 6, 2, 1, 2, 4, 5,
       4, 5, 6, 2, 0, 5])

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred3, labels=[1,0])
ac = accuracy_score(y_test, y_pred3)
print(cm)
print(ac)

[[18  0]
 [ 0 16]]
0.825925925925926


In [28]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred3)
print(accuracy)
print(metrics.classification_report(y_test, y_pred3, labels=[1, 0]))

0.825925925925926
              precision    recall  f1-score   support

           1       0.55      0.64      0.59        28
           0       0.55      0.94      0.70        17

   micro avg       0.55      0.76      0.64        45
   macro avg       0.55      0.79      0.64        45
weighted avg       0.55      0.76      0.63        45



In [29]:
from sklearn.ensemble import RandomForestClassifier  
rfc= RandomForestClassifier(n_estimators= 100, criterion="gini")  
rfc.fit(x_train, y_train)  

RandomForestClassifier()

In [30]:
y_pred4 = rfc.predict(x_test)
y_pred4

array([2, 5, 2, 6, 0, 2, 3, 2, 2, 1, 1, 2, 2, 2, 4, 4, 6, 5, 6, 1, 5, 4,
       2, 4, 5, 2, 3, 6, 0, 5, 6, 1, 2, 4, 2, 5, 6, 2, 1, 5, 1, 4, 5, 5,
       1, 1, 1, 2, 2, 5, 4, 3, 2, 6, 2, 4, 6, 2, 1, 0, 3, 1, 2, 1, 2, 6,
       1, 2, 4, 4, 2, 2, 4, 6, 3, 4, 2, 4, 5, 4, 2, 1, 4, 4, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 1, 2, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 4, 4, 4, 6, 6, 5, 5, 4, 4, 2, 5, 1, 5, 5, 1, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 6, 6, 5, 2, 0, 0, 5, 1, 4, 6, 1,
       6, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 4, 2, 4, 1, 6, 5, 6, 6, 5,
       3, 1, 0, 2, 6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4,
       5, 4, 6, 6, 4, 2, 5, 5, 5, 6, 4, 1, 4, 1, 5, 6, 2, 0, 5, 6, 4, 3,
       6, 2, 6, 2, 2, 0, 2, 5, 2, 4, 0, 2, 1, 4, 2, 2, 4, 6, 5, 5, 5, 5,
       3, 4, 0, 4, 3, 5, 5, 2, 4, 1, 2, 0, 3, 3, 3, 4, 6, 2, 6, 1, 4, 5,
       4, 5, 6, 2, 3, 5])

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred4, labels=[1,0])
ac = accuracy_score(y_test, y_pred4)
print(cm)
print(ac)

[[20  0]
 [ 0 13]]
0.8962962962962963


In [32]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred4)
print(accuracy)
print(metrics.classification_report(y_test, y_pred4, labels=[1, 0]))

0.8962962962962963
              precision    recall  f1-score   support

           1       0.65      0.71      0.68        28
           0       0.81      0.76      0.79        17

   micro avg       0.70      0.73      0.72        45
   macro avg       0.73      0.74      0.73        45
weighted avg       0.71      0.73      0.72        45



In [33]:
from sklearn.svm import SVC 
svm = SVC(kernel='linear', random_state=0)  
svm.fit(x_train, y_train)  

SVC(kernel='linear', random_state=0)

In [34]:
svm = SVC()
svm.fit(x_train, y_train)

SVC()

In [35]:
y_pred5 = svm.predict(x_test)
y_pred5

array([2, 5, 2, 6, 0, 2, 3, 2, 2, 1, 1, 2, 2, 2, 4, 4, 6, 5, 6, 1, 5, 4,
       2, 4, 5, 2, 3, 6, 0, 5, 6, 1, 2, 4, 2, 5, 0, 2, 1, 5, 1, 4, 5, 5,
       1, 1, 1, 2, 2, 5, 4, 3, 2, 6, 2, 4, 6, 2, 2, 0, 3, 1, 2, 1, 2, 6,
       1, 2, 4, 4, 2, 2, 4, 6, 3, 4, 2, 4, 5, 4, 2, 1, 4, 4, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 1, 2, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 4, 4, 4, 1, 1, 5, 5, 4, 4, 2, 5, 1, 5, 5, 6, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 6, 6, 5, 2, 0, 0, 5, 6, 4, 6, 1,
       6, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 4, 2, 4, 1, 6, 5, 6, 6, 5,
       3, 1, 0, 1, 6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 0, 5, 2, 1, 2, 4, 4, 4,
       5, 4, 6, 6, 4, 2, 5, 5, 5, 6, 4, 1, 4, 1, 5, 6, 2, 0, 5, 1, 4, 3,
       6, 1, 6, 2, 2, 3, 2, 5, 2, 4, 0, 2, 6, 4, 2, 2, 4, 6, 5, 5, 5, 5,
       3, 4, 0, 4, 3, 5, 5, 2, 4, 1, 2, 3, 0, 3, 3, 4, 6, 2, 6, 4, 4, 5,
       4, 5, 6, 2, 3, 5])

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred5, labels=[1,0])
ac = accuracy_score(y_test, y_pred5)
print(cm)
print(ac)

[[22  0]
 [ 0 15]]
0.9222222222222223


In [37]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred5)
print(accuracy)
print(metrics.classification_report(y_test, y_pred5, labels=[1, 0]))

0.9222222222222223
              precision    recall  f1-score   support

           1       0.71      0.79      0.75        28
           0       0.88      0.88      0.88        17

   micro avg       0.77      0.82      0.80        45
   macro avg       0.80      0.83      0.81        45
weighted avg       0.77      0.82      0.80        45



In [38]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [39]:
y_pred6 = gnb.predict(x_test)
y_pred6

array([2, 5, 2, 6, 3, 2, 3, 2, 2, 1, 1, 2, 2, 2, 4, 6, 6, 5, 6, 1, 5, 4,
       2, 4, 5, 2, 3, 6, 0, 5, 6, 1, 2, 4, 2, 5, 0, 2, 1, 5, 1, 4, 5, 5,
       1, 1, 1, 2, 2, 5, 4, 3, 2, 6, 2, 4, 6, 2, 1, 3, 3, 1, 2, 1, 2, 6,
       1, 2, 4, 4, 2, 2, 4, 6, 3, 4, 2, 4, 5, 4, 2, 1, 4, 0, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 1, 1, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 6, 4, 4, 1, 1, 5, 5, 4, 4, 2, 5, 1, 5, 5, 6, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 6, 6, 5, 2, 0, 0, 5, 1, 4, 6, 1,
       6, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 0, 2, 4, 1, 6, 5, 6, 6, 5,
       3, 1, 0, 1, 6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4,
       5, 4, 6, 6, 4, 2, 5, 5, 5, 6, 4, 1, 4, 1, 5, 6, 2, 0, 5, 6, 4, 0,
       6, 1, 6, 2, 2, 0, 2, 5, 2, 6, 0, 2, 1, 4, 2, 2, 4, 6, 5, 5, 5, 5,
       3, 4, 0, 4, 3, 5, 5, 2, 4, 1, 1, 0, 3, 3, 3, 4, 6, 2, 6, 1, 4, 5,
       4, 5, 6, 2, 3, 5])

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred6, labels=[1,0])
ac = accuracy_score(y_test, y_pred6)
print(cm)
print(ac)

[[22  0]
 [ 0 12]]
0.8666666666666667


In [41]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred6)
print(accuracy)
print(metrics.classification_report(y_test, y_pred6, labels=[1, 0]))

0.8666666666666667
              precision    recall  f1-score   support

           1       0.61      0.79      0.69        28
           0       0.67      0.71      0.69        17

   micro avg       0.63      0.76      0.69        45
   macro avg       0.64      0.75      0.69        45
weighted avg       0.63      0.76      0.69        45



In [42]:
from sklearn.preprocessing import MinMaxScaler
mns = MinMaxScaler()
x_train = mns.fit_transform(x_train)
x_test = mns.transform(x_test)

In [43]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train, y_train)

MultinomialNB()

In [44]:
y_pred7 = mnb.predict(x_test)
y_pred7

array([2, 5, 2, 4, 3, 2, 5, 2, 2, 2, 4, 2, 2, 2, 4, 4, 4, 5, 2, 2, 5, 4,
       2, 4, 5, 2, 4, 4, 4, 5, 6, 2, 2, 4, 2, 5, 6, 2, 2, 5, 2, 4, 5, 5,
       2, 2, 2, 2, 2, 5, 4, 3, 2, 4, 2, 4, 4, 2, 2, 3, 5, 4, 2, 2, 2, 4,
       2, 2, 4, 4, 2, 2, 4, 4, 5, 4, 2, 4, 5, 4, 2, 2, 4, 4, 2, 4, 2, 5,
       4, 2, 2, 5, 5, 5, 4, 2, 2, 2, 2, 4, 4, 5, 2, 5, 5, 4, 5, 4, 4, 2,
       5, 2, 4, 4, 4, 2, 2, 5, 5, 4, 4, 2, 5, 2, 5, 5, 4, 2, 4, 4, 2, 2,
       5, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 2, 6, 5, 2, 4, 5, 5, 2, 4, 4, 2,
       4, 5, 2, 2, 2, 5, 5, 2, 4, 5, 0, 4, 2, 4, 2, 4, 2, 4, 5, 2, 2, 5,
       3, 2, 4, 2, 4, 5, 2, 5, 2, 5, 2, 0, 0, 5, 4, 5, 2, 4, 2, 4, 4, 4,
       5, 4, 2, 6, 4, 2, 5, 5, 5, 4, 4, 2, 4, 4, 5, 6, 2, 0, 5, 2, 4, 4,
       2, 2, 5, 2, 2, 4, 2, 5, 2, 4, 4, 2, 4, 4, 2, 5, 4, 6, 5, 5, 5, 5,
       5, 4, 0, 4, 5, 5, 5, 2, 4, 2, 2, 4, 5, 5, 5, 4, 2, 2, 6, 4, 4, 5,
       4, 5, 5, 2, 5, 5])

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred7, labels=[1,0])
ac = accuracy_score(y_test, y_pred7)
print(cm)
print(ac)

[[0 0]
 [0 5]]
0.6814814814814815


In [46]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred7)
print(accuracy)
print(metrics.classification_report(y_test, y_pred7, labels=[1, 0]))

0.6814814814814815
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        28
           0       0.83      0.29      0.43        17

   micro avg       0.83      0.11      0.20        45
   macro avg       0.42      0.15      0.22        45
weighted avg       0.31      0.11      0.16        45



C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
