In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\DELL\Desktop\Python Program\Data Science\heart.csv")

In [4]:
df.shape

(918, 12)

In [5]:
df.head(5)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [6]:
df.tail(5)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0

In [8]:
df['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [10]:
df['ChestPainType'] = df['ChestPainType'].replace(['ATA'],'0')
df['ChestPainType'] = df['ChestPainType'].replace(['NAP'],'1')
df['ChestPainType'] = df['ChestPainType'].replace(['ASY'],'2')
df['ChestPainType'] = df['ChestPainType'].replace(['TA'],'3')
df


Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M             0        140          289          0     Normal   
1     49   F             1        160          180          0     Normal   
2     37   M             0        130          283          0         ST   
3     48   F             2        138          214          0     Normal   
4     54   M             1        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M             3        110          264          0     Normal   
914   68   M             2        144          193          1     Normal   
915   57   M             2        130          131          0     Normal   
916   57   F             0        130          236          0        LVH   
917   38   M             1        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [11]:
df['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [13]:
df['RestingECG'] = df['RestingECG'].replace(['Normal'],'0')
df['RestingECG'] = df['RestingECG'].replace(['ST'],'1')
df['RestingECG'] = df['RestingECG'].replace(['LVH'],'2')
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M             0        140          289          0          0   
1     49   F             1        160          180          0          0   
2     37   M             0        130          283          0          1   
3     48   F             2        138          214          0          0   
4     54   M             1        150          195          0          0   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M             3        110          264          0          0   
914   68   M             2        144          193          1          0   
915   57   M             2        130          131          0          0   
916   57   F             0        130          236          0          2   
917   38   M             1        138          175          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [14]:
df['ExerciseAngina'].unique()

array(['N', 'Y'], dtype=object)

In [15]:
df['ExerciseAngina'] = df['ExerciseAngina'].replace(['N'],'0')
df['ExerciseAngina'] = df['ExerciseAngina'].replace(['Y'],'1')
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M             0        140          289          0          0   
1     49   F             1        160          180          0          0   
2     37   M             0        130          283          0          1   
3     48   F             2        138          214          0          0   
4     54   M             1        150          195          0          0   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M             3        110          264          0          0   
914   68   M             2        144          193          1          0   
915   57   M             2        130          131          0          0   
916   57   F             0        130          236          0          2   
917   38   M             1        138          175          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              0      0.0       Up             0  
1      156              0      1.0     Flat             1  
2       98              0      0.0       Up             0  
3      108              1      1.5     Flat             1  
4      122              0      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              0      1.2     Flat             1  
914    141              0      3.4     Flat             1  
915    115              1      1.2     Flat             1  
916    174              0      0.0     Flat             1  
917    173              0      0.0       Up             0  

[918 rows x 12 columns]

In [16]:
df['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [17]:
df['ST_Slope'] = df['ST_Slope'].replace(['Up'],'0')
df['ST_Slope'] = df['ST_Slope'].replace(['Flat'],'1')
df['ST_Slope'] = df['ST_Slope'].replace(['Down'],'2')
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M             0        140          289          0          0   
1     49   F             1        160          180          0          0   
2     37   M             0        130          283          0          1   
3     48   F             2        138          214          0          0   
4     54   M             1        150          195          0          0   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M             3        110          264          0          0   
914   68   M             2        144          193          1          0   
915   57   M             2        130          131          0          0   
916   57   F             0        130          236          0          2   
917   38   M             1        138          175          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              0      0.0        0             0  
1      156              0      1.0        1             1  
2       98              0      0.0        0             0  
3      108              1      1.5        1             1  
4      122              0      0.0        0             0  
..     ...            ...      ...      ...           ...  
913    132              0      1.2        1             1  
914    141              0      3.4        1             1  
915    115              1      1.2        1             1  
916    174              0      0.0        1             1  
917    173              0      0.0        0             0  

[918 rows x 12 columns]

In [18]:
df['Sex'] = df['Sex'].replace(['M'],'0')
df['Sex'] = df['Sex'].replace(['F'],'1')
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   0             0        140          289          0          0   
1     49   1             1        160          180          0          0   
2     37   0             0        130          283          0          1   
3     48   1             2        138          214          0          0   
4     54   0             1        150          195          0          0   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   0             3        110          264          0          0   
914   68   0             2        144          193          1          0   
915   57   0             2        130          131          0          0   
916   57   1             0        130          236          0          2   
917   38   0             1        138          175          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              0      0.0        0             0  
1      156              0      1.0        1             1  
2       98              0      0.0        0             0  
3      108              1      1.5        1             1  
4      122              0      0.0        0             0  
..     ...            ...      ...      ...           ...  
913    132              0      1.2        1             1  
914    141              0      3.4        1             1  
915    115              1      1.2        1             1  
916    174              0      0.0        1             1  
917    173              0      0.0        0             0  

[918 rows x 12 columns]

In [19]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [21]:
y=df['HeartDisease']
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [22]:
x=df.drop(['HeartDisease'],axis=1)
x

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   0             0        140          289          0          0   
1     49   1             1        160          180          0          0   
2     37   0             0        130          283          0          1   
3     48   1             2        138          214          0          0   
4     54   0             1        150          195          0          0   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   0             3        110          264          0          0   
914   68   0             2        144          193          1          0   
915   57   0             2        130          131          0          0   
916   57   1             0        130          236          0          2   
917   38   0             1        138          175          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  
0      172              0      0.0        0  
1      156              0      1.0        1  
2       98              0      0.0        0  
3      108              1      1.5        1  
4      122              0      0.0        0  
..     ...            ...      ...      ...  
913    132              0      1.2        1  
914    141              0      3.4        1  
915    115              1      1.2        1  
916    174              0      0.0        1  
917    173              0      0.0        0  

[918 rows x 11 columns]

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression
LG = LogisticRegression()
LG.fit(x_train, y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
y_pred = LG.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
print(confusion_matrix(y_test, y_pred, labels=[1,0]))

[[143  21]
 [ 17  95]]


In [29]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.8623188405797102
              precision    recall  f1-score   support

           1       0.89      0.87      0.88       164
           0       0.82      0.85      0.83       112

    accuracy                           0.86       276
   macro avg       0.86      0.86      0.86       276
weighted avg       0.86      0.86      0.86       276



In [30]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN.fit(x_train, y_train)

KNeighborsClassifier()

In [31]:
y_pred = KNN.predict(x_test)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

[[122  42]
 [ 36  76]]
0.717391304347826
              precision    recall  f1-score   support

           1       0.77      0.74      0.76       164
           0       0.64      0.68      0.66       112

    accuracy                           0.72       276
   macro avg       0.71      0.71      0.71       276
weighted avg       0.72      0.72      0.72       276



In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [35]:
y_pred = dtc.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[123  41]
 [ 21  91]]
0.7753623188405797


In [37]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.7753623188405797
              precision    recall  f1-score   support

           1       0.85      0.75      0.80       164
           0       0.69      0.81      0.75       112

    accuracy                           0.78       276
   macro avg       0.77      0.78      0.77       276
weighted avg       0.79      0.78      0.78       276



In [38]:
from sklearn.ensemble import RandomForestClassifier  
RFC= RandomForestClassifier(n_estimators= 100, criterion="gini")  
RFC.fit(x_train, y_train)

RandomForestClassifier()

In [39]:
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [40]:
y_pred = rfc.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[145  19]
 [ 16  96]]
0.8731884057971014


In [42]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.8731884057971014
              precision    recall  f1-score   support

           1       0.90      0.88      0.89       164
           0       0.83      0.86      0.85       112

    accuracy                           0.87       276
   macro avg       0.87      0.87      0.87       276
weighted avg       0.87      0.87      0.87       276



In [43]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [44]:
y_pred = gnb.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[142  22]
 [ 14  98]]
0.8695652173913043


In [46]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.8695652173913043
              precision    recall  f1-score   support

           1       0.91      0.87      0.89       164
           0       0.82      0.88      0.84       112

    accuracy                           0.87       276
   macro avg       0.86      0.87      0.87       276
weighted avg       0.87      0.87      0.87       276



In [48]:
from sklearn.preprocessing import MinMaxScaler
mns = MinMaxScaler()
x_train = mns.fit_transform(x_train)
x_test = mns.transform(x_test)

In [49]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train, y_train)

MultinomialNB()

In [50]:
y_pred = mnb.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[143  21]
 [ 27  85]]
0.8260869565217391


In [52]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.8260869565217391
              precision    recall  f1-score   support

           1       0.84      0.87      0.86       164
           0       0.80      0.76      0.78       112

    accuracy                           0.83       276
   macro avg       0.82      0.82      0.82       276
weighted avg       0.83      0.83      0.83       276



In [53]:
from sklearn.svm import SVC 
svm = SVC(kernel='linear', random_state=0)  
svm.fit(x_train, y_train) 

SVC(kernel='linear', random_state=0)

In [54]:
svm = SVC()
svm.fit(x_train, y_train)

SVC()

In [55]:
y_pred = svm.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[151  13]
 [ 16  96]]
0.894927536231884


In [57]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.894927536231884
              precision    recall  f1-score   support

           1       0.90      0.92      0.91       164
           0       0.88      0.86      0.87       112

    accuracy                           0.89       276
   macro avg       0.89      0.89      0.89       276
weighted avg       0.89      0.89      0.89       276

