In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\DELL\Desktop\Python Program\Data Science\HepatitisCdata.csv")

In [3]:
df.shape

(615, 14)

In [4]:
df.head()

Unnamed: 0       Category  Age Sex   ALB   ALP   ALT   AST   BIL    CHE  \
0           1  0=Blood Donor   32   m  38.5  52.5   7.7  22.1   7.5   6.93   
1           2  0=Blood Donor   32   m  38.5  70.3  18.0  24.7   3.9  11.17   
2           3  0=Blood Donor   32   m  46.9  74.7  36.2  52.6   6.1   8.84   
3           4  0=Blood Donor   32   m  43.2  52.0  30.6  22.6  18.9   7.33   
4           5  0=Blood Donor   32   m  39.2  74.1  32.6  24.8   9.6   9.15   

   CHOL   CREA   GGT  PROT  
0  3.23  106.0  12.1  69.0  
1  4.80   74.0  15.6  76.5  
2  5.20   86.0  33.2  79.3  
3  4.74   80.0  33.8  75.7  
4  4.32   76.0  29.9  68.7

In [5]:
df.describe()

Unnamed: 0         Age         ALB         ALP         ALT         AST  \
count  615.000000  615.000000  614.000000  597.000000  614.000000  615.000000   
mean   308.000000   47.408130   41.620195   68.283920   28.450814   34.786341   
std    177.679487   10.055105    5.780629   26.028315   25.469689   33.090690   
min      1.000000   19.000000   14.900000   11.300000    0.900000   10.600000   
25%    154.500000   39.000000   38.800000   52.500000   16.400000   21.600000   
50%    308.000000   47.000000   41.950000   66.200000   23.000000   25.900000   
75%    461.500000   54.000000   45.200000   80.100000   33.075000   32.900000   
max    615.000000   77.000000   82.200000  416.600000  325.300000  324.000000   

              BIL         CHE        CHOL         CREA         GGT        PROT  
count  615.000000  615.000000  605.000000   615.000000  615.000000  614.000000  
mean    11.396748    8.196634    5.368099    81.287805   39.533171   72.044137  
std     19.673150    2.205657    1.132728    49.756166   54.661071    5.402636  
min      0.800000    1.420000    1.430000     8.000000    4.500000   44.800000  
25%      5.300000    6.935000    4.610000    67.000000   15.700000   69.300000  
50%      7.300000    8.260000    5.300000    77.000000   23.300000   72.200000  
75%     11.200000    9.590000    6.060000    88.000000   40.200000   75.400000  
max    254.000000   16.410000    9.670000  1079.100000  650.900000   90.000000

In [6]:
df.isnull().sum()

Unnamed: 0     0
Category       0
Age            0
Sex            0
ALB            1
ALP           18
ALT            1
AST            0
BIL            0
CHE            0
CHOL          10
CREA           0
GGT            0
PROT           1
dtype: int64

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="median")
imputer.fit(df.iloc[:,[4,5,6,10,13]])
df.iloc[:,[4,5,6,10,13]]=imputer.transform(df.iloc[:,[4,5,6,10,13]])

In [8]:
df.isnull().sum()

Unnamed: 0    0
Category      0
Age           0
Sex           0
ALB           0
ALP           0
ALT           0
AST           0
BIL           0
CHE           0
CHOL          0
CREA          0
GGT           0
PROT          0
dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Sex"]=le.fit_transform(df["Sex"])

le = LabelEncoder()
df["Category"]=le.fit_transform(df["Category"])

In [34]:
df.head()

Unnamed: 0  Category  Age  Sex   ALB   ALP   ALT   AST   BIL    CHE  CHOL  \
0           1         0   32    0  38.5  52.5   7.7  22.1   7.5   6.93  3.23   
1           2         0   32    0  38.5  70.3  18.0  24.7   3.9  11.17  4.80   
2           3         0   32    0  46.9  74.7  36.2  52.6   6.1   8.84  5.20   
3           4         0   32    0  43.2  52.0  30.6  22.6  18.9   7.33  4.74   
4           5         0   32    0  39.2  74.1  32.6  24.8   9.6   9.15  4.32   

    CREA   GGT  PROT  
0  106.0  12.1  69.0  
1   74.0  15.6  76.5  
2   86.0  33.2  79.3  
3   80.0  33.8  75.7  
4   76.0  29.9  68.7

In [35]:
y=df['Category']
y

0      0
1      0
2      0
3      0
4      0
      ..
610    4
611    4
612    4
613    4
614    4
Name: Category, Length: 615, dtype: int64

In [36]:
x=df.drop(['Category'],axis=1)
x.iloc[:,1:]

Age  Sex   ALB    ALP    ALT    AST   BIL    CHE  CHOL   CREA    GGT  \
0     32    0  38.5   52.5    7.7   22.1   7.5   6.93  3.23  106.0   12.1   
1     32    0  38.5   70.3   18.0   24.7   3.9  11.17  4.80   74.0   15.6   
2     32    0  46.9   74.7   36.2   52.6   6.1   8.84  5.20   86.0   33.2   
3     32    0  43.2   52.0   30.6   22.6  18.9   7.33  4.74   80.0   33.8   
4     32    0  39.2   74.1   32.6   24.8   9.6   9.15  4.32   76.0   29.9   
..   ...  ...   ...    ...    ...    ...   ...    ...   ...    ...    ...   
610   62    1  32.0  416.6    5.9  110.3  50.0   5.57  6.30   55.7  650.9   
611   64    1  24.0  102.8    2.9   44.4  20.0   1.54  3.02   63.0   35.9   
612   64    1  29.0   87.3    3.5   99.0  48.0   1.66  3.63   66.7   64.2   
613   46    1  33.0   66.2   39.0   62.0  20.0   3.56  4.20   52.0   50.0   
614   59    1  36.0   66.2  100.0   80.0  12.0   9.07  5.30   67.0   34.0   

     PROT  
0    69.0  
1    76.5  
2    79.3  
3    75.7  
4    68.7  
..    ...  
610  68.5  
611  71.3  
612  82.0  
613  71.0  
614  68.0  

[615 rows x 12 columns]

In [30]:
y=df['Category']
y

0      0
1      0
2      0
3      0
4      0
      ..
610    4
611    4
612    4
613    4
614    4
Name: Category, Length: 615, dtype: int32

In [31]:
x=df.drop(['Category'],axis=1)
x.iloc[:,1:]

Age  Sex   ALB    ALP    ALT    AST   BIL    CHE  CHOL   CREA    GGT  \
0     32    0  38.5   52.5    7.7   22.1   7.5   6.93  3.23  106.0   12.1   
1     32    0  38.5   70.3   18.0   24.7   3.9  11.17  4.80   74.0   15.6   
2     32    0  46.9   74.7   36.2   52.6   6.1   8.84  5.20   86.0   33.2   
3     32    0  43.2   52.0   30.6   22.6  18.9   7.33  4.74   80.0   33.8   
4     32    0  39.2   74.1   32.6   24.8   9.6   9.15  4.32   76.0   29.9   
..   ...  ...   ...    ...    ...    ...   ...    ...   ...    ...    ...   
610   62    1  32.0  416.6    5.9  110.3  50.0   5.57  6.30   55.7  650.9   
611   64    1  24.0  102.8    2.9   44.4  20.0   1.54  3.02   63.0   35.9   
612   64    1  29.0   87.3    3.5   99.0  48.0   1.66  3.63   66.7   64.2   
613   46    1  33.0   66.2   39.0   62.0  20.0   3.56  4.20   52.0   50.0   
614   59    1  36.0   66.2  100.0   80.0  12.0   9.07  5.30   67.0   34.0   

     PROT  
0    69.0  
1    76.5  
2    79.3  
3    75.7  
4    68.7  
..    ...  
610  68.5  
611  71.3  
612  82.0  
613  71.0  
614  68.0  

[615 rows x 12 columns]

In [37]:
from sklearn.preprocessing import StandardScaler
SD=StandardScaler()
x=SD.fit_transform(x)


In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [39]:
from sklearn.linear_model import LogisticRegression
LG = LogisticRegression()
LG.fit(x_train, y_train)

LogisticRegression()

In [40]:
y_pred = LG.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
       4, 0, 2, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
       0, 4, 0, 3, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 3, 4, 3, 0, 0, 3, 0, 2,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 2, 2, 0, 3, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0], dtype=int64)

In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
print(confusion_matrix(y_test, y_pred, labels=[1,0]))

[[  2   0]
 [  1 152]]


In [43]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)

0.9243243243243243


In [44]:
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.67      0.67      0.67         3
           0       0.98      0.99      0.99       153

   micro avg       0.97      0.99      0.98       156
   macro avg       0.82      0.83      0.83       156
weighted avg       0.97      0.99      0.98       156



In [45]:
from sklearn.neighbors import KNeighborsClassifier
KNN= KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN.fit(x_train, y_train)

KNeighborsClassifier()

In [46]:
y_pred = KNN.predict(x_test)


In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[  0   3]
 [  0 153]]
0.8648648648648649


In [48]:
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           0       0.88      1.00      0.94       153

   micro avg       0.88      0.98      0.93       156
   macro avg       0.44      0.50      0.47       156
weighted avg       0.86      0.98      0.92       156



C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
from sklearn.tree import DecisionTreeClassifier


In [50]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [51]:
y_pred = dtc.predict(x_test)
y_pred

array([0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       4, 0, 2, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 3, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 3, 4, 2, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0,
       0, 4, 0, 0, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 3, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0], dtype=int64)

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[  1   0]
 [  0 153]]
0.9837837837837838


In [53]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.9837837837837838
              precision    recall  f1-score   support

           1       1.00      0.33      0.50         3
           0       1.00      1.00      1.00       153

   micro avg       1.00      0.99      0.99       156
   macro avg       1.00      0.67      0.75       156
weighted avg       1.00      0.99      0.99       156



In [54]:
from sklearn.ensemble import RandomForestClassifier  
rfc= RandomForestClassifier(n_estimators= 100, criterion="gini")  
rfc.fit(x_train, y_train)  

RandomForestClassifier()

In [55]:
y_pred = rfc.predict(x_test)
y_pred

array([0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       4, 0, 2, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 2, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0,
       0, 4, 0, 0, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 2, 2, 0, 3, 0, 0, 0, 0,
       0, 0, 0, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 3, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0], dtype=int64)

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[  1   1]
 [  0 153]]
0.9783783783783784


In [57]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.9783783783783784
              precision    recall  f1-score   support

           1       1.00      0.33      0.50         3
           0       0.99      1.00      1.00       153

   micro avg       0.99      0.99      0.99       156
   macro avg       1.00      0.67      0.75       156
weighted avg       0.99      0.99      0.99       156



In [58]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [59]:
y_pred = gnb.predict(x_test)
y_pred

array([0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       4, 0, 2, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 4, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 4, 3, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 4, 0, 0, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0], dtype=int64)

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[  2   0]
 [  0 153]]
0.9567567567567568


In [61]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.9567567567567568
              precision    recall  f1-score   support

           1       1.00      0.67      0.80         3
           0       0.97      1.00      0.99       153

   micro avg       0.97      0.99      0.98       156
   macro avg       0.99      0.83      0.89       156
weighted avg       0.98      0.99      0.98       156



In [63]:
from sklearn.preprocessing import MinMaxScaler
mns = MinMaxScaler()
x_train = mns.fit_transform(x_train)
x_test = mns.transform(x_test)

In [64]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train, y_train)

MultinomialNB()

In [65]:
y_pred = mnb.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[  0   3]
 [  0 153]]
0.8324324324324325


In [67]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.8324324324324325
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           0       0.83      1.00      0.91       153

   micro avg       0.83      0.98      0.90       156
   macro avg       0.42      0.50      0.45       156
weighted avg       0.82      0.98      0.89       156



C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [68]:
from sklearn.svm import SVC 
svm = SVC(kernel='linear', random_state=0)  
svm.fit(x_train, y_train)  

SVC(kernel='linear', random_state=0)

In [69]:
svm = SVC()
svm.fit(x_train, y_train)

SVC()

In [70]:
y_pred = svm.predict(x_test)
y_pred

array([0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       4, 0, 2, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
       0, 4, 0, 3, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 2, 4, 2, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0], dtype=int64)

In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred, labels=[1,0])
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[  0   0]
 [  0 153]]
0.9297297297297298


In [72]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

0.9297297297297298
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           0       0.97      1.00      0.98       153

   micro avg       0.97      0.98      0.97       156
   macro avg       0.48      0.50      0.49       156
weighted avg       0.95      0.98      0.97       156



C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
