In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"C:\Users\DELL\Desktop\Python Program\Data Science\Social_Network_Ads.csv")

In [3]:
data.shape

(400, 5)

In [4]:
data.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
data.tail(5)

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
data['Gender'] = data['Gender'].replace(['Male'],'0')
data['Gender'] = data['Gender'].replace(['Female'],'1')
data.head()

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510      0   19            19000          0
1  15810944      0   35            20000          0
2  15668575      1   26            43000          0
3  15603246      1   27            57000          0
4  15804002      0   19            76000          0

In [8]:
data.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [9]:
y=data['Purchased']
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [10]:
x=data.drop(['Purchased'],axis=1)
x=data.drop(['User ID'],axis=1)
x

Gender  Age  EstimatedSalary  Purchased
0        0   19            19000          0
1        0   35            20000          0
2        1   26            43000          0
3        1   27            57000          0
4        0   19            76000          0
..     ...  ...              ...        ...
395      1   46            41000          1
396      0   51            23000          1
397      1   50            20000          1
398      0   36            33000          0
399      1   49            36000          1

[400 rows x 4 columns]

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=150)


In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
clr = LogisticRegression()
clr.fit(x_train, y_train)

LogisticRegression()

In [18]:
y_pred = clr.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
print(confusion_matrix(y_test, y_pred, labels=[1,0]))

[[ 0 34]
 [ 0 86]]


In [21]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)

0.7166666666666667


In [22]:
print(metrics.classification_report(y_test, y_pred, labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        34
           0       0.72      1.00      0.83        86

    accuracy                           0.72       120
   macro avg       0.36      0.50      0.42       120
weighted avg       0.51      0.72      0.60       120



C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [24]:
y_pred1 = classifier.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred1, labels=[1,0])
ac = accuracy_score(y_test, y_pred1)


In [26]:
print(cm)
print(ac)

[[21 13]
 [12 74]]
0.7916666666666666


In [27]:
print(metrics.classification_report(y_test, y_pred1, labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.64      0.62      0.63        34
           0       0.85      0.86      0.86        86

    accuracy                           0.79       120
   macro avg       0.74      0.74      0.74       120
weighted avg       0.79      0.79      0.79       120



In [28]:
from sklearn.tree import DecisionTreeClassifier


In [29]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [30]:
y_pred2 = dtc.predict(x_test)
y_pred2

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred2, labels=[1,0])
ac = accuracy_score(y_test, y_pred2)
print(cm)
print(ac)


[[34  0]
 [ 0 86]]
1.0


In [32]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred2)
print(accuracy)

1.0


In [33]:
print(metrics.classification_report(y_test, y_pred2, labels=[1, 0]))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        34
           0       1.00      1.00      1.00        86

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120



In [34]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="gini")  
classifier.fit(x_train, y_train) 

RandomForestClassifier(n_estimators=10)

In [35]:
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [36]:
y_pred3 = rfc.predict(x_test)
y_pred3

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred3, labels=[1,0])
ac = accuracy_score(y_test, y_pred3)
print(cm)
print(ac)

[[34  0]
 [ 0 86]]
1.0


In [38]:
data.head()

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510      0   19            19000          0
1  15810944      0   35            20000          0
2  15668575      1   26            43000          0
3  15603246      1   27            57000          0
4  15804002      0   19            76000          0

In [39]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred3)
print(accuracy)

1.0


In [40]:
print(metrics.classification_report(y_test, y_pred3, labels=[1, 0]))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        34
           0       1.00      1.00      1.00        86

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120



In [41]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [42]:
y_pred4 = gnb.predict(x_test)
y_pred4

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred4, labels=[1,0])
ac = accuracy_score(y_test, y_pred4)
print(cm)
print(ac)

[[34  0]
 [ 4 82]]
0.9666666666666667


In [44]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred4)
print(accuracy)

0.9666666666666667


In [45]:
print(metrics.classification_report(y_test, y_pred4, labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.89      1.00      0.94        34
           0       1.00      0.95      0.98        86

    accuracy                           0.97       120
   macro avg       0.95      0.98      0.96       120
weighted avg       0.97      0.97      0.97       120



In [46]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train, y_train)

MultinomialNB()

In [47]:
y_pred5 = mnb.predict(x_test)
y_pred5

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred5, labels=[1,0])
ac = accuracy_score(y_test, y_pred5)

In [49]:
print(cm)
print(ac)

[[34  0]
 [13 73]]
0.8916666666666667


In [50]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred5)
print(accuracy)

0.8916666666666667


In [51]:
print(metrics.classification_report(y_test, y_pred5, labels=[1, 0]))

              precision    recall  f1-score   support

           1       0.72      1.00      0.84        34
           0       1.00      0.85      0.92        86

    accuracy                           0.89       120
   macro avg       0.86      0.92      0.88       120
weighted avg       0.92      0.89      0.90       120

